services:
  - docker

# Pre-testing install
install:
  - echo "nothing needs to be installed"

# Scripts to be run
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend xthian82/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push xthian82/udagram-frontend
