apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend-svc
spec:
  type: LoadBalancer
  externalName: udagram-frontend
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: udagram-frontend
